services:
  banword_analyzer:
    image: banword_analyzer:dev
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: banword_analyzer
    ports:
      - "5061:5061/tcp"

networks:
  lighthouse_server:
