services:
  sqlinjection_analyzer:
    image: sqlinjection_analyzer:dev
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: sqlinjection_analyzer
    ports:
      - "5057:5057/tcp"

networks:
  lighthouse_server:
