services:
  word_match_analyzer:
    image: word_match_analyzer:dev
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: word_match_analyzer
    ports:
      - "5056:5056/tcp"

networks:
  lighthouse_server:
