services:
  link_analyzer:
    image: link_analyzer:dev
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: link_analyzer
    ports:
      - "5059:5059/tcp"

networks:
  lighthouse_server:
